---
- name: Setup agent configuration
  template:
    src:  newrelic-infra.yml.j2
    dest: /etc/newrelic-infra.yml
    mode: 0600
  notify: restart newrelic-infra
#  when: nrinfragent_state != "absent"

- name: Ensure the target log file directory exists
  file:
    path:  "{{ newrelic_log_dir }}"
    state: directory
  when:
#  - nrinfragent_state != "absent"
  - newrelic_log_dir is defined
  - nrinfragent_config is defined
  - nrinfragent_config.log_file is defined

- name: Setup the agent service
  service:
    name:    newrelic-infra
    state:   started
    enabled: yes
#  when: nrinfragent_state != "absent"
