---
- name: setup agent repo keys
  rpm_key:
    key: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present
#  when: nrinfragent_os_name|lower == 'suse'

- name: setup agent repo reference
  zypper_repository:
    name: newrelic-infra
    description: New Relic Infrastructure Agent
    repo: http://download.newrelic.com/infrastructure_agent/beta/linux/zypp/sles/{{ansible_distribution_version}}/{{ansible_machine}}/
    runrefresh: "yes"
    auto_import_keys: "yes"
    disable_gpg_check: "yes"
  when: nrinfragent_os_name|lower == 'suse'
#  register: infra_agent_zypper_repo

- name: install agent
  zypper:
    name: newrelic-infra
    state: "{{ nrinfragent_state }}"
#  when: nrinfragent_os_name|lower == 'suse'
