---
- name: Execute set up on a RedHat based system
  include_tasks: install-redhat.yml
  when:
  - nrinfragent_os_name|lower == 'redhat'

- name: Execute set up on a Debian based system
  include_tasks: install-debian.yml
  when:
  - nrinfragent_os_name|lower == 'debian'

- name: Execute set up on a Suse based system
  include_tasks: install-suse.yml
  when:
  - nrinfragent_os_name|lower == 'suse'

- name: Configure the agent for use
  include_tasks: agent-configuration.yml
  when:
  - nrinfragent_state != "absent"
