---
# $Author$
# $Date$
# $Source$

# main task file for newrelic.infr

- name: Display New Relic configuration to be applied
  debug:
    var: nrinfragent_config
    verbosity: 2

#- name: Deconfigure the agent if requested
#  include_tasks: agent-deconfigure.yml
#  when:
#  - nrinfragent_state == "absent"

- name: Execute set up on a RedHat based system
  include_tasks: redhat-install.yml
  when:
  - nrinfragent_os_name|lower == 'redhat'
  - nrinfragent_state != "absent"

- name: Execute set up on a RedHat based system
  include_tasks: redhat-uninstall.yml
  when:
  - nrinfragent_os_name|lower == 'redhat'
  - nrinfragent_state == "absent"

# Need to add uninstall tasks for when state == absent
- name: Execute set up on a Debian based system
  include_tasks: install-debian.yml
  when:
  - nrinfragent_os_name|lower == 'debian'
  - nrinfragent_state != "absent"

# Need to add uninstall tasks for when state == absent
- name: Execute set up on a Suse based system
  include_tasks: install-suse.yml
  when:
  - nrinfragent_os_name|lower == 'suse'
  - nrinfragent_state != "absent"

#- name: Configure the agent for use
#  include_tasks: agent-configure.yml
#  when:
#  - nrinfragent_state != "absent"
