---
- name: Confirm RedHat lsb util is present
  yum:
    name: redhat-lsb-core
    state: present
  register: yum_redhat_lsb_result

- name: Display the lsb status
  debug:
    var: yum_redhat_lsb_result
    verbosity: 2


# Only do this if redhat-lsb-core was not initially present
- name: Re-read ansible_lsb facts
  setup:
    filter: ansible_lsb*

- name: Setup agent repo keys
  rpm_key:
    key: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present

- name: Display the repo download URL
  debug:
    msg: "https://download.newrelic.com/infrastructure_agent/linux/yum/el/{{ (ansible_distribution == 'Amazon') | ternary('6', nrinfragent_os_version) }}/x86_64"
    verbosity: 2

- name: Setup agent repo reference
  yum_repository:
    baseurl: "https://download.newrelic.com/infrastructure_agent/linux/yum/el/{{ (ansible_distribution == 'Amazon') | ternary('6', nrinfragent_os_version) }}/x86_64"
    gpgcheck: "yes"
    gpgkey: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    name: 'newrelic-infra'
    repo_gpgcheck: "yes"
    state: present
    description: New Relic Infrastructure
  register: setup_agent_repo

- name: Run make cache to actually import gpg key
  command: "yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra'"
  when:
  - setup_agent_repo.changed
  tags:
    - skip_ansible_lint
  args:
    warn: false

- name: Install agent
  yum:
    name: "newrelic-infra{{ nrinfragent_version }}"
    state: "{{ nrinfragent_state }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure the agent for use
  include_tasks: agent-configure.yml
