---
# $Author$
# $Date$
# $Source$

# Uninstall the Newrelic Infrastructure agent from a Suse server
- name: Deconfigure the agent if requested
  include_tasks: agent-deconfigure.yml

- name: Deinstall agent
  zypper:
    name: newrelic-infra
    state: absent

- name: Setup agent repo reference
  zypper_repository:
    name: newrelic-infra
    description: New Relic Infrastructure Agent
    repo: http://download.newrelic.com/infrastructure_agent/beta/linux/zypp/sles/{{ansible_distribution_version}}/{{ansible_machine}}/
    runrefresh: "yes"
    auto_import_keys: "yes"
    disable_gpg_check: "yes"
    state: absent

- name: Setup agent repo keys
  rpm_key:
    key: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: absent
