---
# $Author$
# $Date$
# $Source$

# Set up the Newrelic Infrastructure agent on a Suse server
- name: Setup agent repo keys
  rpm_key:
    key: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present

- name: Setup agent repo reference
  zypper_repository:
    name: newrelic-infra
    description: New Relic Infrastructure Agent
    repo: http://download.newrelic.com/infrastructure_agent/beta/linux/zypp/sles/{{ansible_distribution_version}}/{{ansible_machine}}/
    runrefresh: "yes"
    auto_import_keys: "yes"
    disable_gpg_check: "yes"
    state: present

- name: Install agent
  zypper:
    name: newrelic-infra
    state: "{{ nrinfragent_state }}"

- name: Configure the agent for use
  include_tasks: agent-configure.yml
